### ISSUE TITLE
b49e6ae breaks plugin - for me, at least

### ISSUE THREAD

**Issue by marcusfschmidt** [dmadisetti/AirLatex.vim#29]
I manually set the cookie by inspection in FF. I noticed that upon updating to b49e6ae, the plugin no longer works for me when :AirLatex is run, instead giving me error messages about airmount. Downgrading to f9b361d fixes the issue. 

Below the error message I get. Without much thought, I tried making airmount.py executable - but no dice.
```
Error detected while processing function remote#define#CommandBootstrap[5]..remote#define#request:
line    2:
error caught in request handler '/home/mafrsc/.local/share/nvim/lazy/AirLatex.vim/rplugin/python3/airlatex:command:AirLatex []'
Traceback (most recent call last):
  File "/home/mafrsc/.pyenv/versions/nvimvenv/lib/python3.11/site-packages/pynvim/plugin/host.py", line 141, in _on_request
    rv = handler(*args)
         ^^^^^^^^^^^^^^
  File "/home/mafrsc/.pyenv/versions/nvimvenv/lib/python3.11/site-packages/pynvim/plugin/host.py", line 102, in _wrap_delayed_function
    plugin = cls(self._configure_nvim_for(cls))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mafrsc/.local/share/nvim/lazy/AirLatex.vim/rplugin/python3/airlatex/__init__.py", line 43, in __init__
    self.nvim.command("let g:AirLatexOutputMountJob = jobstart(['airmount', '-f', "
  File "/home/mafrsc/.pyenv/versions/nvimvenv/lib/python3.11/site-packages/pynvim/api/nvim.py", line 311, in command
    return self.request('nvim_command', string, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mafrsc/.pyenv/versions/nvimvenv/lib/python3.11/site-packages/pynvim/api/nvim.py", line 199, in request
    res = self._session.request(name, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mafrsc/.pyenv/versions/nvimvenv/lib/python3.11/site-packages/pynvim/msgpack_rpc/session.py", line 139, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: function remote#define#CommandBootstrap[5]..remote#define#request, line 2: Vim(let):E475: Invalid value for argument cmd: 'airmount' is not executable
Error invoking '/home/mafrsc/.local/share/nvim/lazy/AirLatex.vim/rplugin/python3/airlatex:command:AirLatex' on channel 3 (python3-rplugin-host):
NvimError("function remote#define#CommandBootstrap[5]..remote#define#request, line 2: Vim(let):E475: Invalid value for argument cmd: 'airmount' is not executable")
Traceback (most recent call last):
  File "/home/mafrsc/.pyenv/versions/nvimvenv/lib/python3.11/site-packages/pynvim/msgpack_rpc/session.py", line 246, in handler
    rv = self._request_cb(name, args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mafrsc/.pyenv/versions/nvimvenv/lib/python3.11/site-packages/pynvim/api/nvim.py", line 232, in filter_request_cb
    result = request_cb(name, args)  # type: ignore[misc]
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mafrsc/.pyenv/versions/nvimvenv/lib/python3.11/site-packages/pynvim/plugin/host.py", line 141, in _on_request
    rv = handler(*args)
         ^^^^^^^^^^^^^^
  File "/home/mafrsc/.pyenv/versions/nvimvenv/lib/python3.11/site-packages/pynvim/plugin/host.py", line 102, in _wrap_delayed_function
    plugin = cls(self._configure_nvim_for(cls))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mafrsc/.local/share/nvim/lazy/AirLatex.vim/rplugin/python3/airlatex/__init__.py", line 43, in __init__
    self.nvim.command("let g:AirLatexOutputMountJob = jobstart(['airmount', '-f', "
pynvim.api.common.NvimError: function remote#define#CommandBootstrap[5]..remote#define#request, line 2: Vim(let):E475: Invalid value for argument cmd: 'airmount' is not executable
```

Using nvim v0.10.0 and python 3.11.

**Comment by dmadisetti** [comment]
Oh woops, I don't think I had notifications turned on for this repo. Sorry.

Yes, I think that's an easy patch
